model_list:
  - model_name: deepseek-chat
    litellm_params:
      model: deepseek/deepseek-chat
      api_key: os.environ/DEEPSEEK_API_KEY

general_settings:
  master_key: os.environ/LITELLM_MASTER_KEY
  disable_spend_logs: true
  disable_error_logs: true
  disable_no_log_param: true

litellm_settings:
  set_verbose: false
  json_logs: true
  drop_params: true
