"use client";

import { useEffect, useState } from "react";
import { createGatewayApi, GatewayApiError } from "@gateway/api-client";
import { Badge, Button, Card } from "@gateway/ui";
import { ConsoleFrame, pickWorkspace, type ConsoleContext, type WorkspaceMembership } from "../console-frame";

type Key = { id: string; name: string; key_prefix: string; status: string; created_at: string; last_used_at: string | null };
export default function ApiKeysPage() { const [context, setContext] = useState<ConsoleContext>(); const [keys, setKeys] = useState<Key[]>([]); const [name, setName] = useState(""); const [secret, setSecret] = useState(""); const [message, setMessage] = useState(""); const [error, setError] = useState(""); const [busy, setBusy] = useState(false);
  useEffect(() => { void loadContext().then((next) => { setContext(next); if (next) void refresh(next); }); }, []);
  async function loadContext() { const result = await createGatewayApi().request<{ memberships: WorkspaceMembership[] }>("/v1/account/context"); return pickWorkspace(result.memberships); }
  async function refresh(next = context) { if (!next) return; const result = await createGatewayApi().request<{ keys: Key[] }>(`/v1/account/organizations/${next.organizationId}/workspaces/${next.workspaceId}/api-keys`); setKeys(result.keys); }
  async function createKey() { if (!context) return; setError(""); setBusy(true); try { const result = await createGatewayApi().request<{ secret: string }>(`/v1/account/organizations/${context.organizationId}/workspaces/${context.workspaceId}/api-keys`, { method: "POST", body: JSON.stringify({ name, environment: "live" }) }); setSecret(result.secret); setName(""); setMessage("Copy this secret now; it will not be shown again."); await refresh(); } catch (cause) { setError(cause instanceof GatewayApiError ? cause.code : "Unable to create API key"); } finally { setBusy(false); } }
  async function revoke(id: string) { if (!context || !window.confirm("Revoke this key?")) return; setError(""); try { await createGatewayApi().request(`/v1/account/organizations/${context.organizationId}/workspaces/${context.workspaceId}/api-keys/${id}/revoke`, { method: "POST" }); await refresh(); } catch (cause) { setError(cause instanceof GatewayApiError ? cause.code : "Unable to revoke API key"); } }
  return <ConsoleFrame active="API keys">{context ? <><header className="console-header"><div><span className="eyebrow">ACCESS CONTROL</span><h1>API keys</h1></div><div className="inline-form"><input value={name} onChange={(event) => setName(event.target.value)} placeholder="Key name" autoComplete="off" /><Button disabled={busy || !name.trim()} onClick={() => void createKey()}>{busy ? "Creating…" : "Create live key"}</Button></div></header>{error ? <Card><p className="form-error">{error}</p></Card> : null}{message ? <Card><p className="muted">{message}</p><code className="secret-block">{secret}</code></Card> : null}<Card><div className="card-heading"><div><span className="eyebrow">WORKSPACE KEYS</span><h2>Credential inventory</h2></div><Badge>{keys.length} keys</Badge></div><div className="data-table">{keys.map((key) => <div className="data-row" key={key.id}><span><strong>{key.name}</strong><small>{key.key_prefix} · created {new Date(key.created_at).toLocaleDateString()}</small></span><Badge tone={key.status === "ACTIVE" ? "positive" : "neutral"}>{key.status}</Badge><Button variant="quiet" disabled={key.status !== "ACTIVE"} onClick={() => void revoke(key.id)}>Revoke</Button></div>)}{keys.length === 0 ? <p className="muted">No API keys yet.</p> : null}</div></Card></> : null}</ConsoleFrame>; }
